In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [6]:
np.logspace(0, 1)

array([ 1.        ,  1.04811313,  1.09854114,  1.1513954 ,  1.20679264,
        1.26485522,  1.32571137,  1.38949549,  1.45634848,  1.52641797,
        1.59985872,  1.67683294,  1.75751062,  1.84206997,  1.93069773,
        2.02358965,  2.12095089,  2.22299648,  2.32995181,  2.44205309,
        2.55954792,  2.6826958 ,  2.8117687 ,  2.9470517 ,  3.0888436 ,
        3.23745754,  3.39322177,  3.55648031,  3.72759372,  3.90693994,
        4.09491506,  4.29193426,  4.49843267,  4.71486636,  4.94171336,
        5.17947468,  5.42867544,  5.68986603,  5.96362332,  6.25055193,
        6.55128557,  6.86648845,  7.19685673,  7.54312006,  7.90604321,
        8.28642773,  8.68511374,  9.10298178,  9.54095476, 10.        ])

In [7]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [8]:
np.ones((4, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.empty((20))

array([ 4.68661952e-310,  0.00000000e+000,  6.92767255e-310,
       -1.19705639e-051,  6.92767254e-310,  6.92767255e-310,
       -1.25869495e+062,  6.92767254e-310,  6.92767255e-310,
        3.20613021e+173,  6.92767254e-310,  6.92767255e-310,
        6.33120832e+145,  6.92767254e-310,  4.68661952e-310,
       -6.61248730e+013,  6.92767254e-310,  4.68661952e-310,
       -6.02150955e+116,  6.92767254e-310])

In [11]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros_like(np.array([[1],[3],[5]]))

array([[0],
       [0],
       [0]])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[2, 2] = 114514
arr

array([[     1,      2,      3],
       [     4,      5,      6],
       [     7,      8, 114514]])

In [15]:
a = np.arange(16).reshape(4, 4)
a[0:3, 0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [16]:
x = np.array([0, 1, 2, 1])
a[x == 1]
# same as a[[False, True, False, True]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [17]:
a = np.arange(16).reshape(4, 4)
b = np.floor(5*np.random.random( (2, 4) ))
c = np.ceil(6*np.random.random( (4, 2) ))
d = np.vstack([a, b])
e = np.hstack([a, c])
print(d, '\n'); print(e)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [ 3.  1.  3.  1.]
 [ 2.  2.  4.  0.]] 

[[ 0.  1.  2.  3.  3.  5.]
 [ 4.  5.  6.  7.  4.  3.]
 [ 8.  9. 10. 11.  3.  4.]
 [12. 13. 14. 15.  5.  1.]]


In [18]:
a = np.arange(16).reshape(4, 4)
b = np.vsplit(a, 2)
c = np.hsplit(a, 4)
print("vertically split: ", b[0], b[1], sep='\n')
print("horizontally split: ", c[0], c[1], c[2], c[3], sep='\n')

vertically split: 
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
horizontally split: 
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [19]:
a = np.array([[0, 3, 4], [1, 6, 4]])
b = a.sum()
print(f'{b = }')
c1 = sum(a) 
print(f'{c = }')
c2 = np.sum(a, axis=0)
print(f'{c2 = }')
c3 = np.sum(a, axis=1)
print(f'{c3 = }')
c4 = np.sum(a, axis=0, keepdims=True)
print(f'{c4 = }')
print(f'{c2.shape = }\n{c4.shape = }')

b = 18
c = [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
c2 = array([1, 9, 8])
c3 = array([ 7, 11])
c4 = array([[1, 9, 8]])
c2.shape = (3,)
c4.shape = (1, 3)


In [20]:
# 矩阵的逐个乘法
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 2, 3], [4, 5, 6]])
c = np.array([1, 2, 0])
print(f'{a*c = }')
d = np.array([[3], [4]])
print(f'{a*d = }')

a*c = array([[ 1,  4,  0],
       [ 4, 10,  0]])
a*d = array([[ 3,  6,  9],
       [16, 20, 24]])


In [21]:
# 矩阵乘法
a = np.ones(4)          # 一维向量(len=3)
b = np.arange(2, 10, 2) # 同上
print(a, b, a@b, sep='\n')

[1. 1. 1. 1.]
[2 4 6 8]
20.0


In [22]:
a = np.ones(shape=(2, 3))
b = np.ones(shape=(4, 2))
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [23]:
from numpy import linalg as LA
a = np.array([[0, 3, 4], [1, 6, 4]])
print(np.round(LA.norm(a, axis=1), 4))
print(np.round(LA.norm(a, axis=0), 4))
print(np.round((LA.norm(a, axis=None)), 4))

[5.     7.2801]
[1.     6.7082 5.6569]
8.8318


In [24]:
a = np.eye(4)
b = np.rot90(a)
b

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])