In [1]:
import cvxpy as cp
import numpy as np
import pandas as pd
import sympy as sp
sp.init_printing(use_unicode=True)
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif']=['Times New Roman + SimSun + WFM Sans SC']
plt.rcParams['mathtext.fontset']='cm'
# Times New Roman + SimSun + WFM Sans SC
# simsum宋体, times new roman -*, simhei黑体, kaiti楷体, 
# dengxian等线, fangsong仿宋, Microsoft Yahei微软雅黑
plt.rcParams['axes.unicode_minus']=False   
plt.rcParams['figure.dpi'] = 200
# plt.rcParams['figure.figsize'] = [4, 3]
# plt.rcParams['font.size'] = 12
plt.rcParams['xtick.direction'] = 'in'
plt.rcParams['ytick.direction'] = 'in'

### 1

In [2]:
x = cp.Variable(2, pos=True)
obj = cp.Maximize(72*x[0] + 64*x[1])
cons = [
    x[0] + x[1] <= 50,
    12*x[0] + 8*x[1] <= 480,
    3*x[0] <= 100,
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[20. 30.]
最优值为：3360.0


(None, None)

### 2

In [3]:
x = cp.Variable(5, integer=True)
c = [20, 90, 80, 70, 30]
obj = cp.Minimize(c @ x)
cons = [
    x[0] + x[1] + x[4] >= 30,
    x[2] + x[3] >= 30,
    3*x[0] + 2*x[2] <= 120,
    3*x[1] + 2*x[3] + x[4] <= 48,
    x >= 0
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[30.  0.  6. 24.  0.]
最优值为：2760.0


(None, None)

### 3
见 4.3 模型二

### 4
企业安排生产问题

In [4]:
x = cp.Variable(2, integer=True)
c = np.array([[0, 5], [6, 2], [1, 1]])
b = np.array([15, 24, 5]).T
p = np.array([2, 1])

prob = cp.Problem(cp.Maximize(p @ x), [c@x <= b, x >= 0])
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[4. 0.]
最优值为：8.0


(None, None)

### 5
标准指派问题

In [5]:
n = 6
x = cp.Variable((n, n), integer=True)
C = pd.read_csv('../../hw/04第4章  线性规划和整数规划模型习题解答/ti4_5.txt', header=None)
C = np.array(C).reshape(n, n)
C

array([[ 6,  7,  5,  8,  9, 10],
       [ 6,  3,  7,  9,  3,  8],
       [ 8, 11, 12,  6,  7,  9],
       [ 9,  7,  5,  4,  7,  6],
       [ 5,  8,  9,  6, 10,  7],
       [ 9,  8,  7,  6,  5,  9]])

In [6]:
obj = cp.Minimize(cp.sum(cp.multiply(C, x))) # cp.sum?
cons = [
    cp.sum(x, axis=0) == 1,
    cp.sum(x, axis=1) == 1,
    0 <= x, x <= 1,
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[[0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
最优值为：30.0


(None, None)

### 6
#### 限制运量的最小费用运输问题

In [7]:
df = pd.read_csv('../../hw/04第4章  线性规划和整数规划模型习题解答/ti4_6_1.txt', sep='\t', header=None)
C = df.values
demand = C[:, -1][:-1]
reserve = C[-1, :][:-1]
C = C[:-1, :-1]

x = cp.Variable(C.shape, pos=True)
obj = cp.Minimize(cp.sum(cp.multiply(C, x)))
cons = [
    cp.sum(x, axis=1) == demand,
    cp.sum(x, axis=0) <= reserve,
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[[  -0.   -0.   -0.   -0.   -0. 3000.   -0.   -0.]
 [  -0.   -0.   -0.   -0. 3100.   -0.   -0.   -0.]
 [  -0.   -0.    0.   -0.   -0.   -0.   -0. 2900.]
 [  -0.   -0. 3100.   -0.   -0.   -0.   -0.   -0.]
 [3100.   -0.   -0.   -0.   -0.   -0.   -0.   -0.]
 [  -0.   -0.   -0. 3400.   -0.   -0.   -0.   -0.]
 [  -0. 3500.   -0.   -0.   -0.   -0.   -0.   -0.]
 [  -0.   -0.   -0. 3200.   -0.   -0.   -0.   -0.]
 [  -0. 3000.   -0.   -0.   -0.   -0.   -0.   -0.]
 [  -0.   -0.   -0.   -0.   -0.   -0.   -0. 3100.]
 [  -0.   -0.   -0.   -0.   -0.   -0. 3300.   -0.]
 [  -0.   -0.   -0.   -0.   -0.   -0. 3200.   -0.]
 [  -0.   -0.   -0.   -0.   -0.   -0. 3300.   -0.]
 [  -0.   -0.   -0.   -0.   -0.   -0.   -0. 2900.]
 [  -0.   -0.   -0.   -0.   -0.   -0.   -0. 3100.]]
最优值为：9244730.0


(None, None)

In [8]:
y = cp.Variable(C.shape, integer=True)
cons = [
    cp.sum(x, axis=1) == demand,
    cp.sum(x, axis=0) <= reserve,
    1000*y <= x, x <= 2000*y,
    0 <= y, y <= 1,
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[[   0.   -0.   -0.   -0. 1000. 2000.   -0.    0.]
 [  -0.    0.   -0.   -0. 2000. 1100.   -0.   -0.]
 [  -0.    0. 1000.   -0.   -0.   -0.   -0. 1900.]
 [  -0.    0. 2000.   -0. 1100.   -0.   -0.   -0.]
 [2000.    0.   -0. 1100.   -0.   -0.   -0.   -0.]
 [1400.    0.   -0. 2000.   -0.   -0.   -0.   -0.]
 [1500. 2000.   -0.   -0.   -0.   -0.   -0.   -0.]
 [  -0.   -0.   -0. 2000. 1200.   -0.   -0.    0.]
 [1000. 2000.   -0.   -0.   -0.   -0.   -0.    0.]
 [  -0.   -0. 1100.   -0.   -0.   -0.   -0. 2000.]
 [  -0.   -0.   -0.   -0.   -0.   -0. 2000. 1300.]
 [  -0.   -0.   -0. 1200.   -0.   -0. 2000.    0.]
 [   0.   -0.   -0. 1300.   -0.   -0. 2000.    0.]
 [  -0.   -0. 1000.   -0.   -0.   -0.   -0. 1900.]
 [  -0.   -0.   -0. 1100.   -0.   -0.   -0. 2000.]]
最优值为：12682750.0


(None, None)

### 7
#### 面试顺序问题

问题分析：安排4名同学的面试顺序，使完成全部面试所花费的时间最少。

符号解释：

$t_{ij}$：第 $i$ 名同学参加完第 $j$ 阶段面试需要的时间
  
$x_{ij}$：第 $i$ 名同学参加第 $j$ 阶段面试的开始时间
  
$y_{ik}$：第 $k$ 名同学是否先于第 $i$ 名同学

$T$：完成全部面试试所花费的最少时间

目标函数：
$$
{\rm min}\ T
$$
约束条件：

1. 时间先后次序约束：每人只有参加完前一个阶段的面试后才能进入下一个阶段

$$
x_{ij} + t_{ij} \leq x_{i,j+1}, \quad i=1,2,3,4,\ j=1,2
$$

2. 每个阶段 $j$ 同一时间只能面试 $1$ 名同学
$$
\begin{align*}
&x_{ij}+t_{ij}-x_{kj} \leq \infty\cdot y_{ik}, \quad i,k=1,2,3,4, \ i<k, \ j=1,2,3\\
&x_{kj}+t_{kj}-x_{ij} \leq \infty\cdot \left( 1-y_{ik} \right) \quad i,k=1,2,3,4,\ i<k, \ j=1,2,3
\end{align*}
$$

3. 完成面试所需的最少时间大于所有人完成第三阶段面试的时刻
$$
x_{i3}+t_{i3} \leq T, \quad i=1,2,3,4
$$
   

In [9]:
df = pd.read_csv('../../hw/04第4章  线性规划和整数规划模型习题解答/ti4_7.txt', sep='\t', header=None)
C = df.values
(personNum, examNum) = C.shape
x = cp.Variable(C.shape, pos=True)
y = cp.Variable((personNum, personNum), integer=True)
T = cp.Variable(pos=True)
obj = cp.Minimize(T)
cons = [
    0 <= y, y <= 1,
    x[:, -1] + C[:, -1] <= T,
    x[:, :-1] + C[:, :-1] <= x[:, 1:],
]
infty = 1e4
for j in range(examNum):    # 对于每个阶段
    for i in range(personNum):  # 对于每位同学
        for k in range(i+1, personNum): # 其他同学...
            cons.append(x[i,j] + C[i,j] - x[k,j] <= infty*y[i,k])
            cons.append(x[k,j] + C[k,j] - x[i,j] <= infty*(1-y[i,k]))
prob = cp.Problem(obj, cons)
prob.solve(solver='SCIP')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[[ 8. 21. 36.]
 [21. 36. 56.]
 [38. 58. 74.]
 [ 0.  8. 18.]]
最优值为：84.0


(None, None)

### 8
背包问题

In [10]:
w = np.array([18,15,23,12])
v = np.array([480,650,580,390])
p = np.array([3100,3800,3500,2850])
W = np.array([10,16,8])
V = np.array([6800,8700,5300])

x = cp.Variable((4,3), nonneg=True)
obj = cp.Maximize(p @ cp.sum(x, axis=1))
ws = (w @ x)
cons = [
    cp.sum(x, axis=0) <= W,
    cp.sum(x, axis=1) <= w,
    v @ x <= V,
    cp.sum(x[:, 0])/10 == cp.sum(x[:, 1])/16,
    cp.sum(x[:, 1])/16 == cp.sum(x[:, 2])/8,
]
prob = cp.Problem(obj, cons)
prob.solve(solver='SCIP')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[[ 0.          0.          0.        ]
 [ 7.          0.          8.        ]
 [ 3.         12.94736842  0.        ]
 [ 0.          3.05263158  0.        ]]
最优值为：121515.78947368423


(None, None)

### 9
钢管下料问题
1. 确定所有合理可行的切割模式

In [11]:
L = 6.9
l = [2.9, 2.1, 1]
demand = [100, 100, 100]
mode = []
r = []
for i in range(int(np.ceil(L/l[0]))):
    for j in range(int(np.ceil(L/l[1]))):
        for k in range(int(np.ceil(L/l[2]))):
            length = i*l[0] + j*l[1] + k*l[2]
            if length > L - min(l) and length <= L:
                mode.append([i, j, k])
                r.append(L - length)

mode = np.array(mode)
r = np.array(r)

mode, r

(array([[0, 0, 6],
        [0, 1, 4],
        [0, 2, 2],
        [0, 3, 0],
        [1, 0, 4],
        [1, 1, 1],
        [2, 0, 1]]),
 array([0.9, 0.8, 0.7, 0.6, 0. , 0.9, 0.1]))

2. 规划

用 $x_{i }$ 表示按照第 $i$ 种模式 $i = 1, 2,\cdots,7$ 切割的原料钢管的根数，以使用的原材料最少为目标

In [12]:
x = cp.Variable(len(mode), integer=True)
obj = cp.Minimize(cp.sum(x))
cons = [
    x @ mode >= demand,
    x >= 0,
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GUROBI')
print(f'最优解为：{x.value}')
print(f'最优值为：{prob.value}')
print(f'余料长度为：{r @ x.value}')

最优解为：[ 0.  1.  0. 33. 14.  0. 43.]
最优值为：91.0
余料长度为：24.900000000000013


附加题：若下料方式不超过三种

$y_i$ 表示是否采用了第 $i$ 种下料方式

In [13]:
x = cp.Variable(len(mode), integer=True)
y = cp.Variable(len(mode), integer=True)
infty = 1e4
obj = cp.Minimize(cp.sum(x))
cons = [
    x @ mode >= demand,
    x <= infty*y,
    cp.sum(y) <= 3,
    x >= 0,
    0 <= y, y <= 1,
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GUROBI')
print(f'最优解为：{x.value}')
print(f'最优值为：{prob.value}')
print(f'余料长度为：{r @ x.value}')

最优解为：[-0. -0. -0. 34. 15. -0. 43.]
最优值为：92.0
余料长度为：24.70000000000001
