---
### 4.1.2 模型求解及应用

#### 1. 企业生产安排问题
1. 决策变量：$x_1$，$x_2$，$x_3$

2. 目标函数：$z=70x_1+50_2+60x_3$

3. 约束条件：$2x_1+4x_2+3_3\leq 150$，$3x_1+x_2+5x_3\leq 160$，$7x_1+3x_2+5x_3\leq 200$，$x_i\geq0,\ i=1, 2, 3$

综上，可以建立数学模型为
$$
\begin{align*}
&{\rm max}\ z=70x_1+50_2+60x_3,\\
&\text{s.t.} \begin{cases}
2x_1+4x_2+3_3\leq 150,\\
3x_1+x_2+5x_3\leq 160,\\
7x_1+3x_2+5x_3\leq 200,\\
x_i\geq0,\ i=1, 2, 3.
\end{cases}
\end{align*}
$$
对于数学规划模型，一定要做灵敏性分析

In [18]:
import cvxpy as cp
from numpy import array
c = array([70, 50, 60])
a = array([[2, 4, 3], [3, 1, 5], [7, 3, 5]])
b = array([150, 160, 200])
x = cp.Variable(3, pos=True)    # pos mean positive
obj = cp.Maximize(c@x)
cons = [a@x <= b]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[15.90909091 29.54545455 -0.        ]
最优值为：2590.909090909091


(None, None)

#### 2. 项目投资问题

In [7]:
import cvxpy as cp
x = cp.Variable((5, 4), pos=True)
p1, p2, p3, p4 = 1.15, 1.25, 1.40, 1.06
obj =  cp.Maximize(p1*x[3,0] + p2*x[2,1] + p3*x[1,2] + p4*x[4,3])
cons = [
    x[0,0] + x[0,3] == 1e5,
    x[1,0] + x[1,2] + x[1,3] == p4*x[0,3],
    x[2,0] + x[2,1] + x[2,3] == p1*x[0,0] + p4*x[1,3],
    x[3,0] + x[3,3] == p1*x[1,0] + p4*x[2,3],
    x[4,3] == p1*x[2,0] + p4*x[3,3],
    x[2,1] <= 4e4,
    x[1,2] <= 3e4
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

# PS: 换成<=同解

最优解为：[[34782.60869565    -0.            -0.         65217.39130435]
 [39130.43478261    -0.         30000.            -0.        ]
 [   -0.         40000.            -0.            -0.        ]
 [45000.            -0.            -0.            -0.        ]
 [   -0.            -0.            -0.            -0.        ]]
最优值为：143750.0


(None, None)

#### 3. 仓库租借问题

In [11]:
import cvxpy as cp
from numpy import array
x = cp.Variable((4,4), pos=True)
obj = cp.Minimize(2800*(x[0,0]+x[1,0]+x[2,0]+x[3,0]) + \
    4500*(x[0,1]+x[1,1]+x[2,1]) + 6000*(x[0,2]+x[1,2]) + 7300*x[0,3])
cons = [
    sum(x[0, :]) >= 15,
    sum(x[0, 1:]) + sum(x[1, :3]) >= 10,
    sum(x[0, 2:]) + sum(x[1, 1:3]) +sum(x[2, :2]) >= 20,
    x[0,3] + x[1,2] + x[2,1] + x[3,0] >= 12
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[[ 3. -0. -0. 12.]
 [-0. -0. -0. -0.]
 [ 8. -0. -0. -0.]
 [-0. -0. -0. -0.]]
最优值为：118400.0


(None, None)

#### 4. 最小费用运输问题

In [21]:
import cvxpy as cp
import numpy as np
import pandas as pd

cost = np.genfromtxt('../04第4章  线性规划和整数规划模型/data4_5_1.txt', dtype=float, max_rows=6, usecols=range(8))
sales = np.genfromtxt('../04第4章  线性规划和整数规划模型/data4_5_1.txt', dtype=float, skip_header=6)
production = np.genfromtxt('../04第4章  线性规划和整数规划模型/data4_5_1.txt', dtype=float, max_rows=6, usecols=8)
# However, it is much easier to use .csv or .xlsx

x = cp.Variable((6,8), pos=True)
obj = cp.Minimize(cp.sum(cp.multiply(cost, x)))
cons = [
    cp.sum(x, axis=0) == sales,
    cp.sum(x, axis=1) <= production    
]
prob = cp.Problem(obj, cons)
prob.solve(solver='GLPK_MI')
print(f'最优解为：{x.value}'), print(f'最优值为：{prob.value}')

最优解为：[[-0. 19. -0. -0. 41. -0. -0. -0.]
 [-0. -0. -0. 32. -0. -0. -0.  1.]
 [-0. 12. 22. -0. -0. -0. 17. -0.]
 [-0. -0. -0. -0. -0.  6. -0. 37.]
 [35.  6. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. 26. 26. -0.]]
最优值为：664.0


(None, None)