In [1]:
from scipy.optimize import fsolve, root

In [2]:
fx = lambda x: x**980 - 5.01*x**979 + 7.398*x**978 - 3.388*x**977 - x**3 + 5.01*x**2 - 7.398*x + 3.388

In [3]:
x1 = fsolve(fx, 1.5, maxfev=4000)
x1

array([1.21])

In [4]:
x2 = root(fx, 1.5)
x2

    fjac: array([[-1.]])
     fun: array([-1.23341756e+69])
 message: 'The solution converged.'
    nfev: 319
     qtf: array([2.00183544e+72])
       r: array([2.54210657e+80])
  status: 1
 success: True
       x: array([1.21])

In [5]:
fx = lambda x:[x[0]**2 + x[1]**2 - 1, x[0] - x[1]]
s1 = fsolve(fx, [1, 1])
s1

array([0.70710678, 0.70710678])

In [6]:
s2 = root(fx, [1, 1])
s2

    fjac: array([[-0.81649679, -0.57734998],
       [ 0.57734998, -0.81649679]])
     fun: array([4.4408921e-16, 0.0000000e+00])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-3.64625238e-10,  2.57828785e-10])
       r: array([-1.73205167, -0.57735171,  1.63299357])
  status: 1
 success: True
       x: array([0.70710678, 0.70710678])

In [7]:
from scipy.integrate import quad
def fx(x):
    return a*x**2 + b*x
a = 2; b = 1
quad(fx, 0, 1)

(1.1666666666666665, 1.2952601953960159e-14)

In [8]:
a, b = 2, 10
quad(fx, 0, 1)

(5.666666666666667, 6.291263806209221e-14)

In [9]:
import numpy as np
from scipy.optimize import least_squares
a = np.loadtxt('../../02第2章  Python使用入门/data2_47.txt')
x0, y0, d = a[0], a[1], a[2]
fx = lambda x: np.sqrt((x0 - x[0])**2 + (y0 - x[1])**2) - d
least_squares(fx, [200, 200])

 active_mask: array([0., 0.])
        cost: 0.367150558463688
         fun: array([-0.3433343 ,  0.13598942, -0.49656114,  0.5927534 ])
        grad: array([-9.77388337e-10,  3.98200473e-10])
         jac: array([[-0.75860568, -0.65155001],
       [-0.11987285, -0.99278925],
       [-0.47376079,  0.88065357],
       [-0.80877665,  0.58811592]])
     message: '`gtol` termination condition is satisfied.'
        nfev: 8
        njev: 8
  optimality: 9.773883369312841e-10
      status: 1
     success: True
           x: array([149.50894334, 359.9847955 ])

In [10]:
from scipy.sparse.linalg import eigs
a = np.array([[1, 2, 3], [2, 1, 3], [3, 3, 6]], dtype=float)
b, c = np.linalg.eig(a)
b, c

(array([ 9.00000000e+00, -1.00000000e+00,  2.80739441e-18]),
 array([[-4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
        [-4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
        [-8.16496581e-01,  4.65265867e-17,  5.77350269e-01]]))

In [11]:
d, e = eigs(a, 1)
d, e

(array([9.+0.j]),
 array([[0.40824829+0.j],
        [0.40824829+0.j],
        [0.81649658+0.j]]))