In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

### 1
TOPSIS 法

In [2]:
data = np.loadtxt('../../../hw/14第14章  综合评价方法习题解答/ti14_1.txt').T
scaler = MinMaxScaler(feature_range=(0, 1)).fit(data)
B = scaler.transform(data)

def small2big(data, to_transform):
    for i in to_transform:
        data[:, i] = 1 - data[:, i]

to_transform = [0, 4, 6, 8]    # 极小型指标
small2big(B, to_transform)

C_pos = B.max(axis=0)
C_neg = B.min(axis=0)
d_pos = np.linalg.norm(B - C_pos, axis=1)
d_neg = np.linalg.norm(B - C_neg, axis=1)
score = d_neg/(d_neg+d_pos)
print("TOPSIS 评价值：\n", np.round(score, 4), sep='')

rank = np.argsort(np.argsort(-score)) + 1
print("\nTOPSIS 排名:\n", rank, sep='')

TOPSIS 评价值：
[0.5133 0.4295 0.5817 0.4253 0.501 ]

TOPSIS 排名:
[2 4 1 5 3]


### 2
灰色关联度分析

In [10]:
data = np.loadtxt('../../../hw/14第14章  综合评价方法习题解答/ti14_2.txt').T
scaler = MinMaxScaler(feature_range=(0, 1)).fit(data)
B = scaler.transform(data)

def small2big(data, to_transform):
    for i in to_transform:
        data[:, i] = 1 - data[:, i]

to_transform = [1, 2, 3]    # 极小型指标
small2big(B, to_transform)

b0 = np.max(B, axis=0)
r = 0.5                 # 分辨系数
Bmin, Bmax = np.min(abs(B - b0)), np.max(abs(B - b0))
co_co = (Bmin + r*Bmax) / (abs(b0 - B) + r*Bmax)
print("灰色关联系数：\n", np.round(co_co, 4), sep='')
score = np.sum(co_co, axis=1)/len(co_co[0])
print("\n灰色关联度：\n", np.round(score, 4), sep='')

rank = np.argsort(np.argsort(-score)) + 1
print("\n灰色关联度排名(降序):\n", rank, sep='')

灰色关联系数：
[[0.3333 0.4046 0.56   0.3333 0.48   0.5238 0.6    0.5172 0.4146]
 [0.4706 0.7681 0.3333 0.434  0.6    1.     0.3846 0.3333 0.68  ]
 [1.     0.3333 0.4828 0.4694 0.3636 0.4783 1.     0.7143 1.    ]
 [0.5333 1.     0.6087 0.5111 1.     0.3333 0.4286 1.     0.4595]
 [0.4    0.5354 0.4516 1.     0.48   0.5238 0.3333 0.3846 0.3333]
 [0.6667 0.6235 1.     0.5897 0.3333 0.6471 0.375  0.6522 0.6296]]

灰色关联度：
[0.463  0.556  0.6491 0.6527 0.4936 0.613 ]

灰色关联度排名(降序):
[6 4 2 1 5 3]
