---
### 14.4.1 模糊数学基本概念
- 论域 $U$
  
- 隶属函数 $M(u)$
- 模糊集的过渡点 $u\ {\rm s.t.}\ M(u)=0.5$
- 模糊集 $M=(M(u_1), M(u_2), \cdots, M(u_n))$
- 模糊分布（定义在实数域上的隶属函数）
- 模糊运算
### 14.4.2 模糊贴进度
- 汉明贴进度

- 欧几里得贴进度

In [1]:
import numpy as np

A = np.array([[0.4,0.3,0.5,0.3],[0.3,0.3,0.4,0.4],[0.2,0.3,0.3,0.3]])   # A1, A2, A3
B = np.array([0.2,0.3,0.4,0.3])
# 汉明贴进度
N = []
n = len(A[0])
for i in range(len(A)):
    N.append(1 -sum(np.abs(A[i] - B))/n)
N

[0.925, 0.95, 0.975]

### 14.4.3 模糊综合评价
1. 确定因素集及相应权重向量

2. 确定评语集
3. 确定各个因素对评语集的隶属度函数
4. 建立模糊评判矩阵（选择合适的合成算子）
5. 模糊综合评判

In [2]:
data = np.loadtxt('../../14第14章  综合评价方法/data14_4.txt')
f1 = lambda x: x/8800
f2 = lambda x: 1 - x/8000
f3 = lambda x: ((0<=x) & (x<=5.5))*1 + ((5.5<x) & (x<8))*(8-x)/(8-5.5) + (x>8)*0
f4 = lambda x: 1 - x/200
f5 = lambda x: (x - 50)/(1500 - 50)
R = []
for i in range(len(data)):
    expr = f"f{i+1}(data[{i}])"
    R.append(eval(expr))
R = np.array(R)
print("综合评价矩阵：\n", np.round(R, 4), sep='')

综合评价矩阵：
[[0.5341 0.7614 0.6705 1.     0.8636]
 [0.375  0.3125 0.3375 0.15   0.25  ]
 [1.     0.76   1.     0.4    0.48  ]
 [0.85   0.75   0.8    0.     0.2   ]
 [1.     0.4483 0.6552 0.     0.0345]]


In [3]:
w = np.array([0.25, 0.2, 0.2, 0.1, 0.25])
score = w @ R
print("模糊综合评价值：\n", np.round(score, 4), sep='')

grade = np.argsort(-score)
grade += 1
print("\n模糊综合评价排名(降序)：\n", grade, sep='')

模糊综合评价值：
[0.7435 0.5919 0.6789 0.36   0.3905]

模糊综合评价排名(降序)：
[1 3 2 5 4]


> 详例（建立评语集）：https://zhuanlan.zhihu.com/p/37619616